name: powadize
favicon: null
layout_spectrum: 0.63198
typography_spectrum: 0.62235
title: french powsurfboards
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1c1c1c'
    - '#616161'
    - '#9b9b9b'
    - '#bfbfbf'
  brandStrength: 0
  lightness: 0.625
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
