name: powadize
favicon: null
layout_spectrum: 1
typography_spectrum: 0.34104
title: french powsurfboards
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1c1c1c'
    - '#616161'
    - '#9b9b9b'
    - '#bfbfbf'
  brandStrength: 0
  lightness: 0.6034412807784975
  saturation: 0.9074715536553413
  rhythmicContrast: 0.380412861937657
purpose: []
